# plymouth quits with --retain-splash and leaves the first console in graphics
# mode, where the kernel refuses to switch consoles; Phosh starts right there.
[Service]
TTYPath=/dev/tty1
ExecStartPost=
ExecStartPost=+chvt 1
UtmpIdentifier=tty1
